apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-00-8ab1c823d7f8/my-repository/hello-cloudbuild:21d6d0b240295605d2dac20b0fc5c33ebb6b1815
        ports:
        - containerPort: 8080
